# permissions for end users to view postgresbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: athos
    app.kubernetes.io/managed-by: kustomize
  name: postgresbackup-viewer-role
rules:
- apiGroups:
  - pg.athos.io
  resources:
  - postgresbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pg.athos.io
  resources:
  - postgresbackups/status
  verbs:
  - get
